// ingredients
export const INGREDIENTS_REQUEST = 'INGREDIENTS_REQUEST';
export const INGREDIENTS_SUCCESS = 'INGREDIENTS_SUCCESS';
export const INGREDIENTS_ERROR = 'INGREDIENTS_ERROR';

// currentIngredient
export const SET_INGREDIENT_DETAILS = 'SET_INGREDIENT_DETAILS';
export const RESET_INGREDIENT_DETAILS = 'RESET_INGREDIENT_DETAILS';

// orderItems
export const ADD_BUN = 'ADD_BUN';
export const ADD_TOPPING = 'ADD_TOPPING';
export const DELETE_TOPPING = 'DELETE_TOPPING';
export const UPDATE_TOPPINGS_LIST = 'UPDATE_TOPPINGS_LIST';
export const CLEAR_ORDER_ITEMS = 'CLEAR_ORDER_ITEMS';

// OrderDetails
export const ORDER_REQUEST = 'ORDER_REQUEST';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_ERROR = 'ORDER_ERROR';

export const CLOSE_ORDER_CREATE_DETAILS = 'CLOSE_ORDER_CREATE_DETAILS';

// user
export const USER_CHECK_AUTH_REQUEST = 'USER_CHECK_AUTH_REQUEST';
export const USER_CHECK_AUTH_SUCCESS = 'USER_CHECK_AUTH_SUCCESS';
export const USER_CHECK_AUTH_FAIL = 'USER_CHECK_AUTH_FAIL';

export const userCheckAuth = {
  request: USER_CHECK_AUTH_REQUEST,
  success: USER_CHECK_AUTH_SUCCESS,
  fail: USER_CHECK_AUTH_FAIL,
};

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const userLogin = {
  request: USER_LOGIN_REQUEST,
  success: USER_LOGIN_SUCCESS,
  fail: USER_LOGIN_FAIL,
};

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';

export const userLogout = {
  request: USER_LOGOUT_REQUEST,
  success: USER_LOGOUT_SUCCESS,
  fail: USER_LOGOUT_FAIL,
};

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const userRegister = {
  request: USER_REGISTER_REQUEST,
  success: USER_REGISTER_SUCCESS,
  fail: USER_REGISTER_FAIL,
};

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

export const userProfile = {
  request: USER_PROFILE_REQUEST,
  success: USER_PROFILE_SUCCESS,
  fail: USER_PROFILE_FAIL,
};

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';

export const userUpdateProfile = {
  request: USER_UPDATE_PROFILE_REQUEST,
  success: USER_UPDATE_PROFILE_SUCCESS,
  fail: USER_UPDATE_PROFILE_FAIL,
};

export const USER_FORGOT_PASSWORD_REQUEST = 'USER_FORGOT_PASSWORD_REQUEST';
export const USER_FORGOT_PASSWORD_SUCCESS = 'USER_FORGOT_PASSWORD_SUCCESS';
export const USER_FORGOT_PASSWORD_FAIL = 'USER_FORGOT_PASSWORD_FAIL';

export const userForgotPassword = {
  request: USER_FORGOT_PASSWORD_REQUEST,
  success: USER_FORGOT_PASSWORD_SUCCESS,
  fail: USER_FORGOT_PASSWORD_FAIL,
};

export const USER_RESET_PASSWORD_REQUEST = 'USER_RESET_PASSWORD_REQUEST';
export const USER_RESET_PASSWORD_SUCCESS = 'USER_RESET_PASSWORD_SUCCESS';
export const USER_RESET_PASSWORD_FAIL = 'USER_RESET_PASSWORD_FAIL';

export const userResetPassword = {
  request: USER_RESET_PASSWORD_REQUEST,
  success: USER_RESET_PASSWORD_SUCCESS,
  fail: USER_RESET_PASSWORD_FAIL,
};

// ws all orders
export const WS_ALL_ORDERS_CONNECTION_START = 'WS_ALL_ORDERS_CONNECTION_START';
export const WS_ALL_ORDERS_CONNECTION_FINISH = 'WS_ALL_ORDERS_CONNECTION_FINISH';

export const WS_ALL_ORDERS_CONNECTION_SUCCESS = 'WS_ALL_ORDERS_CONNECTION_SUCCESS';
export const WS_ALL_ORDERS_CONNECTION_ERROR = 'WS_ALL_ORDERS_CONNECTION_ERROR';
export const WS_ALL_ORDERS_CONNECTION_CLOSED = 'WS_ALL_ORDERS_CONNECTION_CLOSED';

export const WS_GET_ALL_ORDERS = 'WS_GET_ALL_ORDERS';

export const SET_ORDER_DETAILS = 'SET_ORDERS_DETAILS';
export const RESET_ORDER_DETAILS = 'RESET_ORDERS_DETAILS';

export const wsAllOrdersActions = {
  wsAllOrdersInit: WS_ALL_ORDERS_CONNECTION_START,
  wsAllOrdersClose: WS_ALL_ORDERS_CONNECTION_FINISH,
  onOpenAllOrders: WS_ALL_ORDERS_CONNECTION_SUCCESS,
  onErrorAllOrders: WS_ALL_ORDERS_CONNECTION_ERROR,
  onCloseAllOrders: WS_ALL_ORDERS_CONNECTION_CLOSED,
  getAllOrders: WS_GET_ALL_ORDERS,
};

// ws user orders
export const WS_USER_ORDERS_CONNECTION_START = 'WS_USER_ORDERS_CONNECTION_START';
export const WS_USER_ORDERS_CONNECTION_FINISH = 'WS_USER_ORDERS_CONNECTION_FINISH';

export const WS_USER_ORDERS_CONNECTION_SUCCESS = 'WS_USER_ORDERS_CONNECTION_SUCCESS';
export const WS_USER_ORDERS_CONNECTION_ERROR = 'WS_USER_ORDERS_CONNECTION_ERROR';
export const WS_USER_ORDERS_CONNECTION_CLOSED = 'WS_USER_ORDERS_CONNECTION_CLOSED';

export const WS_GET_USER_ORDERS = 'WS_GET_USER_ORDERS';

export const wsUserOrdersActions = {
  wsUserOrdersInit: WS_USER_ORDERS_CONNECTION_START,
  wsUserOrdersClose: WS_USER_ORDERS_CONNECTION_FINISH,
  onOpenUserOrders: WS_USER_ORDERS_CONNECTION_SUCCESS,
  onErrorUserOrders: WS_USER_ORDERS_CONNECTION_ERROR,
  onCloseUserOrders: WS_USER_ORDERS_CONNECTION_CLOSED,
  getUserOrders: WS_GET_USER_ORDERS,
};
